---
# tasks file for mytomrole
  - name: install tomcat7
    apt:
      name: tomcat7
      state: present
  - name: copy tom7 configfiles to node
    template:
      src: templates/myconfig.j2
      dest: etc/default/tomcat7
    notify: restarttomcat7
  - name: install additional packages
     apt:
       name: "{{item}}"
       state: present
       loop:
          - tomcat7-docs 
          - tomcat7-admin
          - tomcat7-examples
  - name: copy tomusers into all nodes
     template:
        src: templates/mytomusers.j2
        dest: etc/tomcat7/tomcat-users.xml
     notify:  restarttomcat7
  - name: deploy application into all nodes
    get_url:
       url: https://maha1234.s3-us-west-2.amazonaws.com/mahaLogin.war
       dest: var/lib/tomcat/webapps/
       force_basic_auth: yes
